apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0ovf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qbgy-tenant/rhtap-demo-app/hacbs-test-project-0ovf@sha256:d2cea9629a598359d0bccc8f0b14505f4aeedb612b025843a14d969ad0b3235b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
